name: use-case1          
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gromacs=2020.6
  - matplotlib
  - nglview
  - mdtraj
  - notebook
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
# - openmpi
  - cmake
